environment:
  CIRCLE_TOKEN:
    secure: TQKcepXmTzCNt4+tUBtYpwEQkdSPwFr9A8ugtoMhNbKu/SW1WM1EpjEu6kYXxpQ4
  TRAVIS_TOKEN:
    secure: tR7HXYv3x97q90uvPrjUxKZh7R1+uqKct0HdEcqTbsg=
  GITHUB_TOKEN:
    secure: 3wuEGJsppSKFvdwhp3jprUA9Zkc3WINlc/9oFXjhAR6J05lYMXP7Fl7lXTKpkGZx
install:
  - ps: Install-Product node 8
  - npm i -g npm@latest
  - npm i
build: off
test: off
build_script:
  - npm run asset-compile
artifacts:
  - path: .nexe\**\node.exe
cache:
  - node_modules
